SU-SWS/stanford_media

- config/install/field.field.media.image.field_media_image_caption.yml
- js/stanford_media.dropzonejs.js
- Removed dependency on allowed_formats module
- in similar media selection, make links open a new window.
- asap
- medium
> removed bad dependency

- src/Plugin/MediaEmbedDialog/Image.php
- Protect the user from entering garbage text into the link field.
- asap
- medium
1. in a wysiwyg add an image
1. for the link url enter something like `this wont work`
1. ensure it gives you a form error.
> Validate the link on the image is valid

- src/Plugin/BundleSuggestion/AudioEmbed.php
- src/Plugin/BundleSuggestion/BundleSuggestionBase.php
- src/Plugin/media/Source/AudioEmbedField.php
- tests/src/Unit/Plugin/BundleSuggestion/AudioEmbedTest.php
- Fixed plugins when audio embed field module isnt enabled.
- asap
- high
1. review tests.
> avoid errors if audio embed field isnt enabled

- CHANGELOG.md
- README.md
- composer.json
- src/Form/BulkUpload.php
- src/Form/MediaLibraryFileUploadForm.php
- src/Form/StanfordMediaDialogForm.php
- stanford_media.info.yml
- stanford_media.post_update.php
- tests/src/Unit/Plugin/Field/FieldFormatter/MediaImageFormatterTest.php
- tests/src/Unit/Plugin/Field/FieldFormatter/MediaResponsiveImageFormatterTest.php
https://github.com/SU-SWS/stanford_profile/pull/36
https://github.com/SU-SWS/stanford_text_editor/pull/10
> tag 8.2.0-alpha1

- config/install/core.entity_form_display.media.file.default.yml
- config/install/core.entity_form_display.media.file.media_library.yml
- config/install/core.entity_form_display.media.image.default.yml
- config/install/core.entity_form_display.media.image.media_library.yml
- config/install/core.entity_form_display.media.video.default.yml
- config/install/core.entity_form_display.media.video.media_library.yml
- config/install/core.entity_view_display.media.file.default.yml
- config/install/core.entity_view_display.media.file.media_library.yml
- config/install/core.entity_view_display.media.image.default.yml
- config/install/core.entity_view_display.media.image.media_library.yml
- config/install/core.entity_view_display.media.video.default.yml
- config/install/core.entity_view_display.media.video.media_library.yml
- config/install/field.field.media.file.field_media_file.yml
- config/install/field.field.media.image.field_media_image.yml
- config/install/field.storage.media.field_media_file.yml
- config/install/field.storage.media.field_media_image.yml
- config/install/image.style.responsive_2x_large.yml
- config/install/image.style.responsive_extra_large.yml
- config/install/image.style.responsive_large.yml
- config/install/image.style.responsive_medium.yml
- config/install/image.style.responsive_small.yml
- config/install/media.type.file.yml
- config/install/media.type.image.yml
- config/install/media.type.video.yml
- config/install/responsive_image.styles.full_responsive.yml
- stanford_media.breakpoints.yml
- Updates responsive breakpoints and image styles
- October 18th
- Low
1. Review this code
2. Check out this branch
3. Do a full site install
4. Run tests
5. Manual review of the image styles
- Just this module
- D8CORE-334
> D8CORE-334: Update responsive breakpoints and image styles.

- composer.json
- config/install/core.entity_form_display.media.image.media_library.yml
- src/Plugin/Field/FieldFormatter/MediaResponsiveImageFormatter.php
- stanford_media.install
- tests/src/Unit/Plugin/Field/FieldFormatter/MediaResponsiveImageFormatterTest.php
See https://github.com/SU-SWS/acsf-cardinalsites/pull/49
> Patch focal point for use in media library

- modules/media_duplicate_validation/media_duplicate_validation.info.yml
- stanford_media.info.yml
> Imonroe patch 1

- composer.json
- When does this need to be merged by?
- How critical is this PR?
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
> Updated focal_point patch

- src/Form/MediaLibraryFileUploadForm.php
- https://www.drupal.org/node/3075165
- Sometime before D9
- Low
1. Let the tests do their thing.
> Add file usage service as a constructor param

- .github/workflows/release.yml
- README.md
- Automated pull request created via HAL 9000.  See changes below for details.
- As soon as possible
Added github action to support releases on the master branch, and updated the README with instructions for release.
> D8CORE-1644

- config/install/core.entity_form_display.media.google_form.default.yml
- config/install/core.entity_form_display.media.google_form.media_library.yml
- config/install/core.entity_view_display.media.google_form.default.yml
- config/install/core.entity_view_display.media.google_form.media_library.yml
- config/install/field.field.media.google_form.field_media_google_form.yml
- config/install/field.storage.media.field_media_google_form.yml
- config/install/media.type.google_form.yml
- Copied google forms media type from stanford_profile
- :shrug: 
- low
1. review configs
1. install the module on a fresh vanilla install if you wish
> D8CORE-1197 Google forms media type

- .circleci/config.yml
- composer.json
- See: https://www.drupal.org/project/focal_point/issues/3098235
- Soonish, builds are failing.
- How critical is this PR?
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
> Removes fixed patch

- composer.json
- config/install/field.storage.media.field_media_embeddable_code.yml
- config/install/field.storage.media.field_media_embeddable_oembed.yml
- src/Form/MediaLibraryEmbeddableForm.php
- stanford_media.info.yml
- tests/src/Kernel/Form/MediaLibraryEmbeddableFormTest.php
- tests/src/Kernel/Plugin/Field/FieldFormatter/EmbeddableFormatterTest.php
- tests/src/Kernel/Plugin/media/Source/EmbeddableTest.php
- tests/src/Kernel/Validator/EmbeddableConstraintValidatorTest.php
- tests/src/Unit/Form/MediaLibraryEmbeddableFormTest.php
> fixup! removed field_permissions.

- src/Plugin/Field/FieldFormatter/EmbeddableFormatter.php
- Twitter embed codes target `<a>` tags. so lets display them.
- soon
- medium
> Allow `<a>` tags in embeddable code.

- CHANGELOG.md
- modules/media_duplicate_validation/media_duplicate_validation.info.yml
- modules/media_duplicate_validation/src/Plugin/MediaDuplicateValidation/ColorMean.php
- src/Plugin/Field/FieldFormatter/EmbeddableFormatter.php
- stanford_media.info.yml
- Automated pull request created via HAL 9000.  See changes below for details.
- As soon as possible
The following changes since commit 584cf471c5c60047c29c71589d0147e50cb9d1a2:
8.2.9 (2020-10-05 15:01:30 -0700)
are available in the Git repository at:
./ 
for you to fetch changes up to 6d4c7dc20eb872927b9917df3b7d3e5f05d453d3:
8.2.10 (2020-11-06 13:20:37 -0700)
----------------------------------------------------------------
Ian Monroe (1):
8.2.10
Mike Decker (1):
Add a check for when the mime type of the image is not known
pookmish (1):
Allow <a> tags in embeddable code. (#71)
sws-developers@lists.stanford.edu (1):
Back to dev
CHANGELOG.md                                                       | 7 +++++++
.../media_duplicate_validation/media_duplicate_validation.info.yml | 2 +- …
> "8.x-2.x 8.2.10

- tests/src/Kernel/Plugin/Filter/MediaEmbedMarkupFilterTest.php
- tests/src/Unit/Plugin/BundleSuggestion/BundleSuggestionTestBase.php
- tests/src/Unit/Plugin/Validation/Constraint/GoogleFormsConstraintValidatorTest.php
- Updated phpunit tests so they will pass on phpunit 8 with drupal 9
- whenever
- low
> Adjusted tests to pass on D9

- config/install/media.type.google_form.yml
- src/Plugin/Field/FieldFormatter/GoogleFormFormatter.php
- src/Plugin/media/Source/GoogleForm.php
- tests/src/Kernel/Plugin/Field/FieldFormatter/GoogleFormFormatterTest.php
- tests/src/Kernel/Plugin/media/Source/GoogleFormTest.php
- When does this need to be merged by?
- How critical is this PR?
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
> converted to using metadata values

- .circleci/config.yml
- tests/codeception/acceptance/StanfordMediaCest.php
- Updated circleci to test D8 and D9
- 1/15/2021
- medium
1. review passing tests
> D9 automated Tests

- composer.json
- tests/codeception/acceptance/StanfordMediaCest.php
- Patch drupal core for improved embeddable handling.
- soon would be nice.
- medium
> D8CORE-3425 Patch drupal core for better embeddable handling

- composer.json
- When does this need to be merged by?
- How critical is this PR?
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
> Updated linkit module

- config/schema/stanford_media.schema.yml
- src/Annotation/EmbedValidator.php
- src/Plugin/EmbedValidator/LocalistValidator.php
- src/Plugin/EmbedValidatorBase.php
- src/Plugin/EmbedValidatorInterface.php
- src/Plugin/EmbedValidatorPluginManager.php
- src/Plugin/Validation/Constraint/EmbeddableConstraint.php
- src/Plugin/Validation/Constraint/EmbeddableConstraintValidator.php
- src/Plugin/media/Source/Embeddable.php
- src/Plugin/media/Source/EmbeddableInterface.php
- stanford_media.module
- stanford_media.permissions.yml
- stanford_media.services.yml
- tests/src/Kernel/Plugin/media/Source/EmbeddableTest.php
- tests/src/Unit/Plugin/EmbedValidator/LocalistValidatorTest.php
- tests/src/Unit/Plugin/Validation/Constraint/EmbeddableConstraintValidatorTest.php
- Added a plugin manager for providing embed code validation and processing.
- 9/24
- High
1. Follow steps in [stanford_profile PR](https://github.com/SU-SWS/stanford_profile/pull/450)
> embeddable validator

- stanford_media.module
- What the title says
- 10/6
- medium
2. clear caches
3. Upload an image to the site in any method.
4. download the uploaded image as a new file and verify the metadata is stripped clean.
> D8CORE-4698 Fix image orientation and strip tags upon upload

- composer.json
- src/Plugin/media/Source/Embeddable.php
- stanford_media.info.yml
- Works with: https://github.com/SU-SWS/stanford_profile/pull/462
- In order to improve our control over oEmbeds, this adds a new dependency -- `oembed_providers` module.
- It updates the Embeddable media plugin to use an updated version of Simplecast.
- 11/8/21
- medium
- normal
1. Set up and test as per the instructions in https://github.com/SU-SWS/stanford_profile/pull/462
- Is there a config:export in this PR that changes the config sync directory? N/A
no front end changes
- D8CORE-4878
- SOE Gryphon, which was the original source of the bug.
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit …
> D8CORE-4878: added oEmbed Providers

- .circleci/config.yml
- tests/src/Kernel/Form/BulkUploadFormTest.php
- tests/src/Kernel/Form/StanfordMediaDialogFormTest.php
- tests/src/Unit/Plugin/Validation/Constraint/EmbeddableConstraintValidatorTest.php
- tests/src/Unit/Plugin/Validation/Constraint/GoogleFormsConstraintValidatorTest.php
- When does this need to be reviewed by?
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?
- How urgent is this? (Normal, High)
4. Verify...
- Other PRs
- Anyone who should be notified? …
> Updated tests for D9.3

- tests/src/Unit/Plugin/Validation/Constraint/EmbeddableConstraintValidatorTest.php
- tests/src/Unit/Plugin/Validation/Constraint/GoogleFormsConstraintValidatorTest.php
- When does this need to be reviewed by?
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?
- How urgent is this? (Normal, High)
4. Verify...
- Other PRs
- Anyone who should be notified? …
> Updated unit tests for latest drupal core

- config/schema/stanford_media.schema.yml
- src/Form/MediaLibraryFileUploadForm.php
- src/Plugin/BundleSuggestionManager.php
- src/Plugin/Field/FieldFormatter/MediaImageFormatter.php
- src/Plugin/Field/FieldFormatter/MediaImageFormatterBase.php
- src/Plugin/Field/FieldFormatter/MediaResponsiveImageFormatter.php
- stanford_media.module
- tests/src/Kernel/Plugin/Field/FieldFormatter/MediaImageFormatterTest.php
- tests/src/Unit/Plugin/Field/FieldFormatter/MediaImageFormatterTest.php
- tests/src/Unit/Plugin/Field/FieldFormatter/MediaResponsiveImageFormatterTest.php
- tests/src/Unit/Plugin/Field/FieldFormatter/MultiMediaFormatterTest.php
- tests/src/Unit/Plugin/MediaEmbedDialog/ImageTest.php
- Added an optional configuration to remove the alt text on the image when rendering
- 3/5
- medium
1. Follow steps in https://github.com/SU-SWS/stanford_profile/pull/498
> D8CORE-5180 D8CORE-5227 Remove alt text on people images

- src/Plugin/BundleSuggestionManager.php
- tests/src/Unit/Plugin/BundleSuggestionManagerTest.php
- When does this need to be reviewed by?
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?
- How urgent is this? (Normal, High)
4. Verify...
- Other PRs
- Anyone who should be notified? …
> Added more test

- src/Plugin/BundleSuggestionManager.php
- stanford_media.services.yml
- tests/src/Unit/Plugin/BundleSuggestionManagerTest.php
- Changes bulk update form to respect private upload settings for individual files and the default scheme
- When does this need to be reviewed by?
- 10
- High
4. Verify...
- Other PRs
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g …
> Suggestion for including uri scheme

- .circleci/config.yml
- .github/workflows/tests.yml
- src/Plugin/AbstractIframeValidator.php
- src/Plugin/EmbedValidator/AirtableEmbedValidatorBase.php
- src/Plugin/EmbedValidator/AirtableValidator.php
- src/Plugin/EmbedValidator/GoogleIframeEmbedValidatorBase.php
- src/Plugin/EmbedValidator/GoogleIframeValidator.php
- src/Plugin/EmbedValidator/OutlookCalendarEmbedValidatorBase.php
- src/Plugin/EmbedValidator/OutlookCalendarValidator.php
- src/Plugin/EmbedValidator/SharepointDocumentEmbedValidatorBase.php
- src/Plugin/EmbedValidator/SharepointDocumentValidator.php
- src/Plugin/EmbedValidator/SmartsheetEmbedValidatorBase.php
- src/Plugin/EmbedValidator/SmartsheetValidator.php
- src/Plugin/IframeEmbedValidatorBase.php
- tests/src/Unit/Plugin/EmbedValidator/AirtableValidatorTest.php
- tests/src/Unit/Plugin/EmbedValidator/GoogleIframeValidatorTest.php
- tests/src/Unit/Plugin/EmbedValidator/OutlookCalendarValidatorTest.php
- tests/src/Unit/Plugin/EmbedValidator/SharepointDocumentValidatorTest.php
- tests/src/Unit/Plugin/EmbedValidator/SmartsheetValidatorTest.php
- Generalizes the iframe validators into an abstract class.
- Note, this is set to merge into D8CORE-5128 and is a modification of that branch.
- 7/7
- low
- Normal
4. Verify...
- Other PRs
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9 …
> D8CORE-5036: Generalize iframe embed validation
