SU-SWS/stanford_media

- config/install/views.view.media_entity_browser.yml
- stanford_media.install
- stanford_media.views.inc
- Added view field for source_id from entity usage data
- replaced the usage count with the new source_id, applied aggregation. this eliminated the count on revisions for each entity.
- If a media item is used in different paragraphs, it will count each of those separately still.
- see https://github.com/SU-HSDO/suhumsci/pull/155
- Some day.
- Low
1.Checkout this branch
1. update database
1. create a new page and add a new image/file to it.
1. edit and save (no changes to the node) several times
1. view /admin/content/media page and ensure it shows only 1 use count instead of multiple
> HSD8-309 Ignore revisions for used in count on media list

- src/Plugin/MediaEmbedDialog/File.php
- src/Plugin/MediaEmbedDialog/SoundCloud.php
- src/Plugin/audio_embed_field/Provider/StanfordSoundCloud.php
- Allow users to choose which embed player to use
- Someday
- Low
1. Embed a soundcloud audio
1. ensure "Classic Embed" and "Visual Embed" radio button are visible and function as expected.
> HSD8-549 Allow users to choose which embed player to use

- src/Form/MediaLibraryFileUploadForm.php
- Fixup to prevent php error of undefined index.
- eventually
- low
1. add an image to any content type or wysiwyg
1. review database logs for errors about undefined index `#source_field_name` (several errors come from an [issue in core](https://www.drupal.org/project/drupal/issues/3094397)
1. clear database logs
1. repeat above steps
1. review the `#source_field_name` error is gone
> Prevent php notice by faking another field data

- CHANGELOG.md
- modules/media_duplicate_validation/media_duplicate_validation.info.yml
- stanford_media.info.yml
- Updated responsive breakpoints to match decanter's
- added some styles to ckeditor
- patched focal point contrib and updated the image media type to make use of it.
- Fixed older update hook for some sites.
- Ckeditor text looks better.
- Media in the ckeditor will have a more obvious "Edit media" button.
- Deploy and run update hook.
- none
- https://github.com/SU-SWS/stanford_media/compare/8.x-2.0-alpha1..8.2.0-alpha.2
> 8.2.0-alpha.2

- stanford_media.module
- If a file media type is embed but doesnt have a "Description" provided, make sure to use the media entity's title.
- 2/28
- low
1. clear cache
1. embed a document in a wysiwyg and change the name of the media item after upload.
1. in the wysiwyg click to edit the media item and remove all text from the "Description" field
1. Save and validate the media link is what you named the media entity.
> D8CORE-1343 Use Media name if no description is provided

- .circleci/config.yml
- src/Plugin/Filter/MediaEmbedMarkupFilter.php
- tests/src/Kernel/Plugin/Filter/MediaEmbedMarkupFilterTest.php
- Text editor filter to fix a core issue. 
- Responsive images in the text editor are outputting `<source ..></source>` which is invalid html as the libxml2 library does not support new html5 tags. 
- see: https://www.drupal.org/project/drupal/issues/1333730
- As of 01/31/2020 there has been no movement in the library to support html5
- This PR adds a filter that we can add to the text formats to do the manual string manipulation on the generated output to correct that.
- End of the month (feb)
- Low, as stuff still works but validators don't like it.
1. Check out this branch in our local build of `stanford_profile` 
2. Navigate to and enable the new option in the HTML format `/admin/config/content/formats/manage/stanford_html`
3. Create a new basic page with a WYSIWYG paragraph and …
> D8CORE-1409: Remove duplicate source tag from embedded media.

- src/Plugin/Field/FieldFormatter/MediaImageFormatter.php
- src/Plugin/Field/FieldFormatter/MediaImageFormatterBase.php
- src/Plugin/Field/FieldFormatter/MediaResponsiveImageFormatter.php
- src/Plugin/Field/FieldFormatter/MultiMediaFormatter.php
- tests/src/Kernel/Plugin/Field/FieldFormatter/MultiMediaFormatterTest.php
- tests/src/Unit/Plugin/Field/FieldFormatter/MediaImageFormatterTest.php
- Fixed formatter when the media item has been deleted. https://github.com/SU-SWS/stanford_media/pull/41
- Fixed image formatter when a non-image media item is used.
- Next week
- Medium
1. clear caches
1. create a basic page with a "Media with Caption" paragraph
1. validate it looks good
1. delete the media entity via `/admin/content/media`
1. go back to the page you created
1. validate the page still loads even if theres no image.
> D8CORE-1026 D8CORE-1516 Fix error in field formatters

- .github/auto-label.json
- composer.json
- src/Form/MediaLibraryFileUploadForm.php
- tests/src/Kernel/Form/MediaLibraryFileUploadFormTest.php
- Fixed weirdness when a user cancels/deletes a file after adding it. The user is now brought back to the original form just like they didn't upload anything.
- updated focal_point patch: see https://github.com/SU-SWS/acsf-cardinalsites/pull/136
- 4/8
- medium-high
1. Go to a basic page
1. go to any field that allows images
1. upload an image
1. when you're asked for the alt text, click the X to delete the media item
1. validate you are brought back and can continue like normal.
> D8 core 1706

- src/Plugin/MediaEmbedDialog/Image.php
- tests/src/Unit/Plugin/MediaEmbedDialog/ImageTest.php
- tests/src/Unit/Plugin/MediaEmbedDialog/MediaEmbedDialogTestBase.php
- added caption to the modal of the image in a wysywig so that a user can set the caption text as soon as they check the box to enable a caption
- 4/8
- medium
1. clear caches
1. add an image to any wysywig
1. click the "Edit Media" button
1. check the box "Caption"
1. Enter text in the "Caption Text" box
1. Click "Save"
1. validate the caption text on the image in the wysiwyg is set to what you entered.
> D8CORE-1223 Added caption field to the image modal in wysiwyg

- src/Plugin/Field/FieldFormatter/MediaImageFormatter.php
- src/Plugin/Field/FieldFormatter/MediaImageFormatterBase.php
- src/Plugin/Field/FieldFormatter/MediaResponsiveImageFormatter.php
- src/Plugin/Field/FieldFormatter/MultiMediaFormatter.php
- Disables cache for image field formatters.
- https://www.drupal.org/project/drupal/issues/2099131
- https://www.drupal.org/node/2151609
- Should look into placeholders and `#lazy_builder` https://www.drupal.org/node/2498803
- Next release
- Med-low
1. Create a page and render the same image with multiple view mode options via block, view, or something else.
2. Clear render cache and view page. 
3. All the items should be the same image format
4. Check out this branch
5. Clear render cache
6. Reload page and each image is its own image format.
> Disable cache for image field formatters.

- src/Plugin/Field/FieldFormatter/MediaImageFormatterBase.php
- Moved the cache tags to each entity render array instead of the whole array. This helps when there are empty items in a view.
- soon
- medium
1. trust in the cache :laughing: 
> cache tags

- src/Plugin/Field/FieldFormatter/EmbeddableFormatter.php
- Some flavors of unstructured embeds require `div` elements, which were being stripped out. Added `div` to the list of allowed tags in the field formatter.
- 10/1/2020
- 5 out of 10
1. Pull this branch into your stack.
2. Edit an existing piece of content
3. Add an unstructured embeddable that includes a div.
Here is some convenient sample code:
```
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
<div class='altmetric-embed' data-badge-type='donut' data-doi="10.1038/nature.2012.9872"></div>
```
4. Save the updated content.
5. Verify the div shows up correctly in the spot where the embeddable should be.
- JIRA ticket
- Other PRs
- Any other contextual information that …
> D8CORE-2514: Added div to the list of allowed tags in unstructured embeds

- src/Plugin/MediaEmbedDialog/File.php
- Remove the ability to add a caption to file media type.
- 12/3
- low
1. create a page and embed a pdf or doc file
1. in the edit media dialog, validate you don't have the ability to add a caption to the file.
> D8CORE-2267 Removed caption checkbox from file media

- stanford_media.module
- templates/filter-caption.html.twig
- Removed the template that does nothing
- Since we have some styles for the `caption` class, we'll use a preprocess hook to add that. (for some stupid reason the template in core doesn't use the `attributes` variable.
- :shrug: 
- medium
1. clear cache
1. create an image in the wysiwyg with a caption
1. see it still looks as expected.
> Remove the filter caption template in favor of preprocess hook'

- stanford_media.module
- stanford_media.permissions.yml
- Display a message when editing a media item to inform the user of multiple location affects.
- Lock permission to media entities that are used as default field values
- 4/1
- medium
1. checkout this branch and clear caches
2. use a media item on multiple pages
3. go to the media edit form and verify you see a message at the top about how many places the item is used
4. Log in with a contributor (masquerade is good)
4. try to edit a media entity that is used as a field default value and verify you can't
> Provide a message on media form and lock default field media items

- src/Form/BulkUpload.php
- src/Plugin/BundleSuggestionManager.php
- tests/src/Kernel/Form/BulkUploadFormTest.php
- tests/src/Kernel/Form/MediaLibraryEmbeddableFormTest.php
- tests/src/Kernel/Form/MediaLibraryGoogleFormFormTest.php
- tests/src/Kernel/Form/StanfordMediaFormTestBase.php
- tests/src/Unit/Plugin/BundleSuggestionManagerTest.php
- Prevent access to create media that the user is not allowed.
- ASAP
- High
2. enable intranet `drush sset stanford_intranet 1 && drush cr`
3. go to the bulk upload page `/admin/content/media/add/bulk`
4. Verify you can't upload a pdf or other document.
> D8CORE-4392 Check for media access on bulk upload form

- composer.json
- src/StanfordMedia.php
- stanford_media.module
- tests/src/Unit/StanfordMediaTest.php
- Alter the alt text field help text for images.
- 1/20
- low
2. clear caches
3. go to upload or edit an image media item
4. validate the help text on the alt field is different and contains a link to the uit website.
> D8CORE-5241 Adjust image alt text description

- src/Plugin/MediaEmbedDialog/Image.php
- Modify the alt help text when embedding an image in the WYSIWYG
- 3/5
- low
2. embed an image into a wysiwyg
3. click the "Edit This Media" button in the WYSIWYG
4. verify the alt text help text has changed from the core text.
> D8CORE-5410 Apply the modified alt help text to embedded images

- src/Plugin/MediaEmbedDialog/Image.php
- src/StanfordMedia.php
- tests/src/Unit/Plugin/MediaEmbedDialog/ImageTest.php
- tests/src/Unit/StanfordMediaTest.php
- Add a "Decorative" checkbox on image fields in the media library to enforce empty alt texts
- Allow "unsetting" an alt text in the wysiwyg for decorative images.
- 7/7
- Medium
2. Go to create an image via the media library or the wysiwyg
3. try out the "Decorative image" checkbox
4. create an image with an alt text and add it to the media library.
5. in a wysiwyg, add that image to the body
6. edit the inline image and set it to be decorative
7. save the page
8. verify the image has an empty alt attribute.
> D8CORE-5963 Improve "Decorative" approach to images

- src/Plugin/EmbedValidator/TwitterValidator.php
- tests/src/Unit/Plugin/EmbedValidator/AirtableValidatorTest.php
- tests/src/Unit/Plugin/EmbedValidator/GoogleIframeValidatorTest.php
- tests/src/Unit/Plugin/EmbedValidator/LocalistValidatorTest.php
- tests/src/Unit/Plugin/EmbedValidator/OutlookCalendarValidatorTest.php
- tests/src/Unit/Plugin/EmbedValidator/SharepointDocumentValidatorTest.php
- tests/src/Unit/Plugin/EmbedValidator/SmartsheetValidatorTest.php
- tests/src/Unit/Plugin/EmbedValidator/TwitterValidatorTest.php
- Added twitter embed code validation.
- low
- medium
2. enable the embed validator on the embed code media type
3. go to twitter.com and find some embed code
4. as a site manager, paste the embed code into the media type
5. verify it allows it and the embed code functions as expected on a page.
> HSD8-1338 Add twitter embed code validator

- composer.json
- src/StanfordMedia.php
- src/StanfordMediaInterface.php
- stanford_media.module
- stanford_media.services.yml
- tests/src/Kernel/Form/BulkUploadFormTest.php
- tests/src/Kernel/Form/MediaLibraryEmbeddableFormTest.php
- tests/src/Kernel/Form/MediaLibraryFileUploadFormTest.php
- tests/src/Kernel/Form/MediaLibraryGoogleFormFormTest.php
- tests/src/Kernel/Form/StanfordMediaDialogFormTest.php
- tests/src/Kernel/Plugin/Field/FieldFormatter/MultiMediaFormatterTest.php
- tests/src/Kernel/StanfordMediaTest.php
- tests/src/Kernel/StanfordMediaTestBase.php
- Delete associated files from the server if the media item is deleted
- It will also delete thumbnails that might be different such as when a video media is deleted.
- medium
- medium
2. clear caches
3. create a media item and upload images/files
4. view the file list page to see your files. `/admin/content/files`
5. delete the media item
6. reload the file list page
7. verify your file has been removed.
> HSD8-1340 Clean up files when a media item is deleted
